accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetCompleteView, PasswordResetDoneView, PasswordResetConfirmView


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_form, name='login'),
    path('profil/<str:username>/edit', views.edit_profile, name='edit_profile'),
    path('logout', views.log_out, name='logout'),
    path('<str:username>', views.profile, name='profile'),
    path('follow/profile', views.follow, name='follow'),
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete')




]

posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/post/', views.CreatePost, name="crate_post"),
    path('view/post/<int:post>', views.view_post, name="view_post"),
    path('remove/post/', views.RemovePost, name="remove_post"),
    path('get/comments/', views.get_comments, name='get_comments'),
    path('create/comment/', views.CreateComment, name='creat_comment'),
    path('comment/like/', views.like_comment, name='like_comment'),
    path('remove/comment/', views.remove_comment, name="remove_comment"),
    path('get/replies/', views.get_replies, name='get_replies'),
    path('create/reply/', views.creat_reply, name='create_reply'),
    path('remove/reply/', views.remove_reply, name='remove_reply'),
    path('reply/like/', views.like_reply, name='like_reply'),
    path('posts/count_views/', views.count_post_views, name='count_views'),
    path('post/like/', views.like_button, name='like_btn'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import community



urlpatterns = [
    path('', include('timeline.urls')),
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
    path('', include('notification.urls')),
    # path('', include('community.urls')),
    path('', include('search.urls')),
    path('admin/admin', admin.site.urls),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'posts.views.error_404_view'

accounts/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

import os.path

#################### USER CUSTOMIZE ###################################


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


class Users(AbstractBaseUser):

	GENDER = [
		('Male', 'Male'),
		('Female', 'Female'),
	]



	############### Fields ####################3
	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	first_name				= models.CharField(max_length=30)
	last_name				= models.CharField(max_length=30)
	birthday				= models.DateField(blank=True, null=True)
	gender					= models.CharField(max_length=10, choices=GENDER , null=True, blank=True, default="Male")
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)
	is_online				= models.BooleanField(default=False)
	date_joined 			= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login 				= models.DateTimeField(verbose_name='last login', auto_now=True)
	first_login				= models.BooleanField(default=True)


	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()


	def save(self, *args, **kwargs):
		if not self.username:
			user = Users.objects.all().order_by('-pk').first()
			pk = user.pk + 1
			self.username = f'{self.first_name}{pk}'
		super(Users, self).save(*args, **kwargs)

	def __str__(self):
		return self.username



	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True





###################### PROFILE METHOD ########################

def profile_picture_upload(instance , filename):
	iconname , extension = os.path.splitext(filename)
	return f'profile/{instance.id}/picture/{iconname}.{extension}'

def profile_cover_upload(instance, filename):
	iconname , extension = os.path.splitext(filename)
	return f'profile/{instance.id}/cover/{iconname}.{extension}'

class Profile(models.Model):

	user                = models.OneToOneField(Users, on_delete=models.CASCADE, related_name='profile')
	picture				= models.ImageField(upload_to=profile_picture_upload, default="user-default.png")
	cover				= models.ImageField(upload_to=profile_cover_upload, default="default-cover.jpg")
	bio					= models.TextField(max_length=300, blank=True, null=True)
	followers 			= models.ManyToManyField(Users, related_name='followers', default=None, blank=True)
	following 			= models.ManyToManyField(Users, related_name='following', default=None, blank=True)


	def __str__(self):
		return self.user.username


	@receiver(post_save, sender=Users)
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from .models import Users, Profile





########################### USER SIGNUP FORM #########################

class UserRegistrationForm(UserCreationForm):
    first_name  = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'autocomplete': 'on', 'autofocus' : "on"}))
    last_name   = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'autocomplete': 'on'}))
    email       = forms.CharField(max_length=50, widget=forms.TextInput(attrs= {'placeholder' : "name@example.com", "type" : 'email', 'autocomplete': 'on', }))
    birthday    = forms.CharField(max_length=12, widget=forms.DateTimeInput(attrs={"type": "hidden"}))


    class Meta(UserCreationForm.Meta):
        model = Users
        # I've tried both of these 'fields' declaration, result is the same
        fields = ('first_name', 'last_name', 'email', 'birthday', 'gender', 'password1', 'password2', )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Users.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'





######################## USER LOGIN FORM #######################################

class UserLoginForm(forms.ModelForm):
    email    = forms.EmailField(max_length=100)
    password    = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'autocomplete':'on'}))
    class Meta:
        model = Users
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'





########################### Edit profile form ###############3333


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'pattern' : "[a-zA-Z0-9-._%+-]+", 'title': 'remove all spaces'}))
    birthday = forms.CharField(max_length=12, widget=forms.DateInput(attrs={"type": "hidden"}))
    class Meta:
        model = Users
        fields = ('first_name', 'last_name', 'username', 'email', 'birthday', 'gender',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture', 'bio')

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.contrib.auth import authenticate, logout, login

from .forms import UserRegistrationForm, UserLoginForm, UserForm, ProfileForm
from django.contrib import messages

from .models import Profile, Users
from posts.models import Comment
from notification.models import Notification


from django.conf import settings
import os


from django.http import HttpResponse



# Create your views here.


################################# SIGNUP FORM VIEW #########################

def signup(request):
    user = request.user
    if user.is_authenticated:
        return redirect("timeline_page")
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully registered. Login now')
            return redirect('login')
    else:
        form = UserRegistrationForm()

    context = {

        'form': form
    }

    template = 'registration/sign_up.html'
    return render(request, template, context)




######################### LOGIN FORM VIEW #############################3


def login_form(request):
    user = request.user
    if user.is_authenticated:
        return redirect("timeline_page")
    if request.method == 'POST':
        form = UserLoginForm()
        email       = request.POST['email']
        password    = request.POST['password']
        user        = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            user = Users.objects.get(email=email)
            user.is_online = True
            user.save()
            if user.first_login:
                user.first_login = False
                user.save()
                return redirect("edit_profile", user.username)


            return redirect("timeline_page")
        else:
            messages.warning(request, 'The username and password you entered did not match our records. Please check '
                                      'inputs and try again.')
    else:
        form = UserLoginForm()

    context = {

        'form': form
    }


    template = 'registration/login.html'
    return render(request, template, context)


################################ logout ###################################33

def log_out(request):
    user = Users.objects.get(username=request.user)
    user.is_online = False
    user.save()
    logout(request)
    return redirect('/')







##################### PROFILE VIEW ############################

def profile(request, username):
    x = request.user
    if x.is_authenticated:
        user = Users.objects.get(username=x)
    else:
        user = None

    profile_user = get_object_or_404(Profile, user__username=username)
    posts = profile_user.user.posts.all().order_by('-created_at')
    comments = Comment.objects.all().order_by("-created_at")
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    ### View all media files related to user
    media_root = settings.MEDIA_ROOT
    try:
        pictures   = os.listdir(f'{media_root}/profile/{profile_user.id}/picture')[:3]
        pictures   = reversed(pictures)

    except:
        pictures = None

    try:
        covers      = os.listdir(f'{media_root}/profile/{profile_user.id}/cover')[:3]
        covers      = reversed(covers)
    except:
        covers = None

    try:
        images      = os.listdir(f'{media_root}/profile/{profile_user.id}/posts')[:3]
        images      = reversed(images)
    except:
        images = None



    context = {

        'user': user,
        'profile' : profile_user,
        'pictures' : pictures,
        'covers' : covers,
        'images' : images,
        'media_url' : f"{settings.MEDIA_URL}\profile\{profile_user.id}",
        'posts' : posts,
        'comments': comments,
        'now': timezone.now
    }
    template = 'profile.html'

    return render(request, template, context)



################# Edit profile #############333
def edit_profile(request, username):

    if request.user.is_authenticated:
        user = get_object_or_404(Users, username=username)
        if request.user == user:
            if request.method == 'POST':
                user_form = UserForm(request.POST, instance=user)
                profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
                if user_form.is_valid and profile_form.is_valid :
                    user_form.save()
                    profile_form.save()
                    messages.success(request, 'Your profile has been updated')
                    username = user_form.cleaned_data['username']
                    return redirect('edit_profile', username)
            else:
                user_form = UserForm(instance=user)
                profile_form = ProfileForm(instance=user.profile)

            context = {
                'user_form' : user_form,
                'profile_form' : profile_form
            }
            template = 'edit_profile.html'
            return render(request, template, context)
        else:
            return redirect('timeline_page')
    else:
        return redirect('timeline_page')



############ follow profile #######################

def follow(request):
    if request.user.is_authenticated and request.is_ajax():
        pk = request.GET['id']
        user = Users.objects.get(username=request.user)
        user2 = Users.objects.get(profile=pk)
        profile1 = Profile.objects.get(id=pk)

        following = user.profile.following.all()
        if user2 not in following:
            user.profile.following.add(user2)
            user.profile.save()
            profile1.followers.add(request.user)
            profile1.save()
            Notification.objects.create(type='follow',
                                        sender=user,
                                        user=user2,)
        else:
            user.profile.following.remove(user2)
            user.profile.save()
            profile1.followers.remove(request.user)
            profile1.save()
            try:
                note = Notification.objects.get(type='follow', sender=user, user=user2)
                note.delete()
            except:
                pass




        return HttpResponse('')

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/libs/croppie.css' %}" />
        {% if messages %}
        {% for message in messages %}
            <div style="text-align: center;" class=" m-auto alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="container-fluid">

        <div class="login-form bg-light m-auto mt-5 col-md-6">
            <div style="top: 0px;" class="user-p col">
            <img id="ss" src="{{ user.profile.picture.url }}" alt="pic">
        </div>
            <form class="e-form container" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}

                <div class="form-row text-center">
                    <div class="col-md-6 m-auto">
                        <label for="id_picture" class="btn btn-outline-dark" >Chang profile picture</label>
                        <input type="file" name="picture" accept="image/*" id="id_picture" style="display: none">
                    </div>
                </div><br>
                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="{{ user_form.first_name.id_for_label }}">First Name</label>
                        {{user_form.first_name}}
                        {{ user_form.first_name.errors }}
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="{{ user_form.last_name.id_for_label }}">Last Name</label>
                        {{user_form.last_name}}
                        {{ user_form.lasr_name.errors }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ user_form.username.id_for_label }}">Username</label>
                    {{user_form.username}}
                    {{ user_form.username.errors }}
                </div>
                <div class="form-group">
                    <label for="{{ user_form.email.id_for_label }}">Email</label>
                    {{user_form.email}}
                    {{ user_form.email.errors }}
                </div>
                <div class="form-group">
                    <label for="{{ profile_form.bio.id_for_label }}">Bio</label>
                    {{profile_form.bio}}
                    {{ profile_form.bio.errors }}
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-3">
                        <label for="{{ user_form.gender.id_for_label }}">Gender</label>
                        {{ user_form.gender }}
                        {{ user_form.gender.errors }}
                        {{ user_form.birthday }}
                    </div>

                    <div class="form-row col-sm">
                        <div class="form-group col-sm-4">
                            <label for="inputDay">Day</label>
                            <select id="inputDay" class="form-control"></select>
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="inputMonth">Month</label>
                            <select id="inputMonth" class="form-control"></select>
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="inputYear">Year</label>
                            <select id="inputYear" class="form-control"></select>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="text-center">
                    <span>to save all changes  click this button </span>
                    <input class="btn btn-outline-success" type="submit" value="save">
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/sign_up.js' %}"></script>
   <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          $('#ss').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#id_picture").change(function() {
      readURL(this);
    });
   </script>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="p_h container-fluid">
        <div class="cover-page">
            <div class="modal fade bd-example-modal-lg show" id="cover-{{ profile.user.username }}">
                <div class="modal-dialog">
                        <div class="modal-content" style="background: unset; border: 0;display: unset;top: 50px">
                            <button type="button" class="close" data-dismiss="modal" style=" z-index: 1;width: fit-content; position: inherit;left: 0; color: #fff; top: 39px; outline: none;border-radius: 3px;background-color: #000000;padding: 3px 10px 11px;">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <img src="{{ profile.cover.url }}" class="img-fluid" alt="profile.user.username"/>
                        </div>
                   </div>
            </div>
            <a href="#cover-{{ profile.user.username }}" data-toggle="modal">
                <img src="{{ profile.cover.url }}">
            </a>

        </div>
        <div class="user-p col">
            <div class="modal fade bd-example-modal-lg show" id="picture-{{ profile.user.username }}">
                <div class="modal-dialog">
                        <div class="modal-content" style="background: unset; border: 0;display: unset;top: 50px">
                            <button type="button" class="close" data-dismiss="modal" style="width: fit-content; position: inherit;left: 0; color: #fff; top: 39px; outline: none;border-radius: 3px;background-color: #000000;padding: 3px 10px 11px;">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <img src="{{ profile.picture.url }}" class="img-fluid" alt="profile.user.username"/>
                        </div>
                   </div>
            </div>
            <a href="#picture-{{ profile.user.username }}" data-toggle="modal">
                <img src="{{ profile.picture.url }}">
            </a>

        </div>
        <div class="info-user container m-auto">
            <div class="row row-cols-1 justify-content-center">
                <div class="justify-content-center mb-2">
                    <h2 class="m-auto" >{{ profile.user.first_name }} {{ profile.user.last_name }}</h2>
                </div>
                {% if request.user.is_authenticated %}
                    {% if user != profile %}
                        {% if request.user != profile.user %}
                            <span>
                                {% if request.user in profile.followers.all %}
                                    <input class="btn btn-outline-primary follow-btn" data-key="{{ profile.id }}" type="submit" value="Unfollow">
                                {% else %}
                                    <input class="btn btn-primary follow-btn" data-key="{{ profile.id }}" type="submit" value="Follow">
                                {% endif %}
                            </span>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <div class="row mb-2">
                    <div class="bio col-sm-6" style="overflow-wrap: anywhere;">
                        <span>
                            {% if profile.bio %}
                                {{ profile.bio }}
                            {% endif %}
                        </span>
                    </div>
                </div>

                <div class="container">
                    <div class="row row-cols-md-2 row-cols-1 offset-md-1 m-auto">
                        <div class="career col  row-cols-12 ">
                            <div class="col">
                                <h6>Gender: <span>{{ profile.user.gender }}</span></h6>
                            </div>
                            <div class="col">
                                <h6>Birthday: <span>{{ profile.user.birthday|date:'M,d' }}</span></h6>
                            </div>
                        </div>
                        <div class="career col row-cols-12">
                            <div class="col" >
                                <h6>Followers: <span><a  style="color: #007bff">{{ profile.followers.count }}</a></span></h6>
                                <h6>Following: <span><a  style="color: #007bff">{{ profile.following.count }}</a></span></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2">
            <div class="col-md-4" style="margin-bottom: 25px;">
                <div class="sticky-top"  style=" z-index: unset; top: 77px;">
                    {% if pictures or covers or images %}
                        <div class="photos row row-cols-2 container m-auto">
                        <span class="col-12"><i class="icofont-ui-image" style="color: #4cd433;"></i> Photos</span>
                        <br>
                        {% for picture in pictures %}
                            <img src="{{ media_url }}\picture\{{ picture }}" alt="photo">
                        {% endfor %}
                        {% for cover in covers %}
                            <img src="{{ media_url }}\cover\{{ cover }}" alt="photo">
                        {% endfor %}
                        {% for image in images %}
                            <img src="{{ media_url }}\posts\{{ image }}" alt="photo">
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <br>
            <div id="posts-list" class="container col">
                {% if user == profile.user %}
                    {% include 'create_post.html' %}
                {% endif %}
                <div class="row row-cols-1">
                    <div id="time-line">
                        {% for post in posts %}
                            {% include 'post-box.html' %}
                        {% endfor %}
                    </div>
                    {% if posts.has_next %}
                        <a class="page-more-link" style="display: none" href="?page={{ posts.next_page_number }}">More</a>
                    {% endif %}
                    <div class="loading" style="display: none;">
                        <div class="d-flex justify-content-center">
                            <div class="spinner-border" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}